// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: sentry_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - mobilegateway.protos.SentryService

/// Namespace containing generated types for the "mobilegateway.protos.SentryService" service.
public enum Mobilegateway_Protos_SentryService {
    /// Service descriptor for the "mobilegateway.protos.SentryService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "GetEvent" metadata.
        public enum GetEvent {
            /// Request type for "GetEvent".
            public typealias Input = Mobilegateway_Protos_GetEventRequest
            /// Response type for "GetEvent".
            public typealias Output = Mobilegateway_Protos_GetEventResponse
            /// Descriptor for "GetEvent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService"),
                method: "GetEvent"
            )
        }
        /// Namespace for "GetEvents" metadata.
        public enum GetEvents {
            /// Request type for "GetEvents".
            public typealias Input = Mobilegateway_Protos_GetEventsRequest
            /// Response type for "GetEvents".
            public typealias Output = Mobilegateway_Protos_GetEventsResponse
            /// Descriptor for "GetEvents".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService"),
                method: "GetEvents"
            )
        }
        /// Namespace for "SetSentryMode" metadata.
        public enum SetSentryMode {
            /// Request type for "SetSentryMode".
            public typealias Input = Mobilegateway_Protos_SetSentryModeRequest
            /// Response type for "SetSentryMode".
            public typealias Output = Mobilegateway_Protos_SetSentryModeResponse
            /// Descriptor for "SetSentryMode".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService"),
                method: "SetSentryMode"
            )
        }
        /// Namespace for "SetEnhancedDeterrence" metadata.
        public enum SetEnhancedDeterrence {
            /// Request type for "SetEnhancedDeterrence".
            public typealias Input = Mobilegateway_Protos_SetEnhancedDeterrenceRequest
            /// Response type for "SetEnhancedDeterrence".
            public typealias Output = Mobilegateway_Protos_SetEnhancedDeterrenceResponse
            /// Descriptor for "SetEnhancedDeterrence".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService"),
                method: "SetEnhancedDeterrence"
            )
        }
        /// Namespace for "SetSentryModeAtHome" metadata.
        public enum SetSentryModeAtHome {
            /// Request type for "SetSentryModeAtHome".
            public typealias Input = Mobilegateway_Protos_SetSentryModeAtHomeRequest
            /// Response type for "SetSentryModeAtHome".
            public typealias Output = Mobilegateway_Protos_SetSentryModeAtHomeResponse
            /// Descriptor for "SetSentryModeAtHome".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService"),
                method: "SetSentryModeAtHome"
            )
        }
        /// Namespace for "SetSentryModeAtWork" metadata.
        public enum SetSentryModeAtWork {
            /// Request type for "SetSentryModeAtWork".
            public typealias Input = Mobilegateway_Protos_SetSentryModeAtWorkRequest
            /// Response type for "SetSentryModeAtWork".
            public typealias Output = Mobilegateway_Protos_SetSentryModeAtWorkResponse
            /// Descriptor for "SetSentryModeAtWork".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService"),
                method: "SetSentryModeAtWork"
            )
        }
        /// Namespace for "TurnOffSentryAlarm" metadata.
        public enum TurnOffSentryAlarm {
            /// Request type for "TurnOffSentryAlarm".
            public typealias Input = Mobilegateway_Protos_TurnOffSentryAlarmRequest
            /// Response type for "TurnOffSentryAlarm".
            public typealias Output = Mobilegateway_Protos_TurnOffSentryAlarmResponse
            /// Descriptor for "TurnOffSentryAlarm".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService"),
                method: "TurnOffSentryAlarm"
            )
        }
        /// Descriptors for all methods in the "mobilegateway.protos.SentryService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetEvent.descriptor,
            GetEvents.descriptor,
            SetSentryMode.descriptor,
            SetEnhancedDeterrence.descriptor,
            SetSentryModeAtHome.descriptor,
            SetSentryModeAtWork.descriptor,
            TurnOffSentryAlarm.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "mobilegateway.protos.SentryService" service.
    public static let mobilegateway_protos_SentryService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.SentryService")
}

// MARK: mobilegateway.protos.SentryService (server)

extension Mobilegateway_Protos_SentryService {
    /// Streaming variant of the service protocol for the "mobilegateway.protos.SentryService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetEvent" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_GetEventRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_GetEventResponse` messages.
        func getEvent(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_GetEventRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_GetEventResponse>

        /// Handle the "GetEvents" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_GetEventsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_GetEventsResponse` messages.
        func getEvents(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_GetEventsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_GetEventsResponse>

        /// Handle the "SetSentryMode" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_SetSentryModeRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_SetSentryModeResponse` messages.
        func setSentryMode(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetSentryModeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetSentryModeResponse>

        /// Handle the "SetEnhancedDeterrence" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_SetEnhancedDeterrenceRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_SetEnhancedDeterrenceResponse` messages.
        func setEnhancedDeterrence(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>

        /// Handle the "SetSentryModeAtHome" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_SetSentryModeAtHomeRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_SetSentryModeAtHomeResponse` messages.
        func setSentryModeAtHome(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse>

        /// Handle the "SetSentryModeAtWork" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_SetSentryModeAtWorkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_SetSentryModeAtWorkResponse` messages.
        func setSentryModeAtWork(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse>

        /// Handle the "TurnOffSentryAlarm" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_TurnOffSentryAlarmRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_TurnOffSentryAlarmResponse` messages.
        func turnOffSentryAlarm(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse>
    }

    /// Service protocol for the "mobilegateway.protos.SentryService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Mobilegateway_Protos_SentryService.StreamingServiceProtocol {
        /// Handle the "GetEvent" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetEventRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_GetEventResponse` message.
        func getEvent(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_GetEventRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_GetEventResponse>

        /// Handle the "GetEvents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetEventsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_GetEventsResponse` message.
        func getEvents(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_GetEventsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_GetEventsResponse>

        /// Handle the "SetSentryMode" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_SetSentryModeResponse` message.
        func setSentryMode(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetSentryModeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeResponse>

        /// Handle the "SetEnhancedDeterrence" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetEnhancedDeterrenceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_SetEnhancedDeterrenceResponse` message.
        func setEnhancedDeterrence(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>

        /// Handle the "SetSentryModeAtHome" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeAtHomeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_SetSentryModeAtHomeResponse` message.
        func setSentryModeAtHome(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse>

        /// Handle the "SetSentryModeAtWork" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeAtWorkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_SetSentryModeAtWorkResponse` message.
        func setSentryModeAtWork(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse>

        /// Handle the "TurnOffSentryAlarm" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_TurnOffSentryAlarmRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_TurnOffSentryAlarmResponse` message.
        func turnOffSentryAlarm(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse>
    }

    /// Simple service protocol for the "mobilegateway.protos.SentryService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Mobilegateway_Protos_SentryService.ServiceProtocol {
        /// Handle the "GetEvent" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_GetEventRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_GetEventResponse` to respond with.
        func getEvent(
            request: Mobilegateway_Protos_GetEventRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_GetEventResponse

        /// Handle the "GetEvents" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_GetEventsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_GetEventsResponse` to respond with.
        func getEvents(
            request: Mobilegateway_Protos_GetEventsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_GetEventsResponse

        /// Handle the "SetSentryMode" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_SetSentryModeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_SetSentryModeResponse` to respond with.
        func setSentryMode(
            request: Mobilegateway_Protos_SetSentryModeRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_SetSentryModeResponse

        /// Handle the "SetEnhancedDeterrence" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_SetEnhancedDeterrenceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_SetEnhancedDeterrenceResponse` to respond with.
        func setEnhancedDeterrence(
            request: Mobilegateway_Protos_SetEnhancedDeterrenceRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_SetEnhancedDeterrenceResponse

        /// Handle the "SetSentryModeAtHome" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_SetSentryModeAtHomeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_SetSentryModeAtHomeResponse` to respond with.
        func setSentryModeAtHome(
            request: Mobilegateway_Protos_SetSentryModeAtHomeRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_SetSentryModeAtHomeResponse

        /// Handle the "SetSentryModeAtWork" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_SetSentryModeAtWorkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_SetSentryModeAtWorkResponse` to respond with.
        func setSentryModeAtWork(
            request: Mobilegateway_Protos_SetSentryModeAtWorkRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_SetSentryModeAtWorkResponse

        /// Handle the "TurnOffSentryAlarm" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_TurnOffSentryAlarmRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_TurnOffSentryAlarmResponse` to respond with.
        func turnOffSentryAlarm(
            request: Mobilegateway_Protos_TurnOffSentryAlarmRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_TurnOffSentryAlarmResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Mobilegateway_Protos_SentryService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Mobilegateway_Protos_SentryService.Method.GetEvent.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_GetEventRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_GetEventResponse>(),
            handler: { request, context in
                try await self.getEvent(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_SentryService.Method.GetEvents.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_GetEventsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_GetEventsResponse>(),
            handler: { request, context in
                try await self.getEvents(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_SentryService.Method.SetSentryMode.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetSentryModeRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetSentryModeResponse>(),
            handler: { request, context in
                try await self.setSentryMode(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_SentryService.Method.SetEnhancedDeterrence.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>(),
            handler: { request, context in
                try await self.setEnhancedDeterrence(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_SentryService.Method.SetSentryModeAtHome.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetSentryModeAtHomeRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetSentryModeAtHomeResponse>(),
            handler: { request, context in
                try await self.setSentryModeAtHome(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_SentryService.Method.SetSentryModeAtWork.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetSentryModeAtWorkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetSentryModeAtWorkResponse>(),
            handler: { request, context in
                try await self.setSentryModeAtWork(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_SentryService.Method.TurnOffSentryAlarm.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_TurnOffSentryAlarmRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_TurnOffSentryAlarmResponse>(),
            handler: { request, context in
                try await self.turnOffSentryAlarm(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Mobilegateway_Protos_SentryService.ServiceProtocol {
    public func getEvent(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_GetEventRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_GetEventResponse> {
        let response = try await self.getEvent(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func getEvents(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_GetEventsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_GetEventsResponse> {
        let response = try await self.getEvents(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func setSentryMode(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetSentryModeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetSentryModeResponse> {
        let response = try await self.setSentryMode(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func setEnhancedDeterrence(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse> {
        let response = try await self.setEnhancedDeterrence(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func setSentryModeAtHome(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse> {
        let response = try await self.setSentryModeAtHome(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func setSentryModeAtWork(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse> {
        let response = try await self.setSentryModeAtWork(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func turnOffSentryAlarm(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse> {
        let response = try await self.turnOffSentryAlarm(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Mobilegateway_Protos_SentryService.SimpleServiceProtocol {
    public func getEvent(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_GetEventRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_GetEventResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_GetEventResponse>(
            message: try await self.getEvent(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func getEvents(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_GetEventsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_GetEventsResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_GetEventsResponse>(
            message: try await self.getEvents(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func setSentryMode(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetSentryModeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeResponse>(
            message: try await self.setSentryMode(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func setEnhancedDeterrence(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>(
            message: try await self.setEnhancedDeterrence(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func setSentryModeAtHome(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse>(
            message: try await self.setSentryModeAtHome(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func setSentryModeAtWork(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse>(
            message: try await self.setSentryModeAtWork(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func turnOffSentryAlarm(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse>(
            message: try await self.turnOffSentryAlarm(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: mobilegateway.protos.SentryService (client)

extension Mobilegateway_Protos_SentryService {
    /// Generated client protocol for the "mobilegateway.protos.SentryService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetEvent" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetEventRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_GetEventRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_GetEventResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getEvent<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetEventRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_GetEventRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_GetEventResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetEventResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetEvents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetEventsRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_GetEventsRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_GetEventsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getEvents<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetEventsRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_GetEventsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_GetEventsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetEventsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetSentryMode" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetSentryModeRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetSentryModeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setSentryMode<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetSentryModeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetSentryModeResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetEnhancedDeterrence" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetEnhancedDeterrenceRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetEnhancedDeterrenceRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetEnhancedDeterrenceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setEnhancedDeterrence<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetSentryModeAtHome" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeAtHomeRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetSentryModeAtHomeRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetSentryModeAtHomeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setSentryModeAtHome<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetSentryModeAtHomeResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetSentryModeAtWork" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeAtWorkRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetSentryModeAtWorkRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetSentryModeAtWorkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setSentryModeAtWork<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetSentryModeAtWorkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "TurnOffSentryAlarm" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_TurnOffSentryAlarmRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_TurnOffSentryAlarmRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_TurnOffSentryAlarmResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func turnOffSentryAlarm<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_TurnOffSentryAlarmResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "mobilegateway.protos.SentryService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetEvent" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetEventRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_GetEventRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_GetEventResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getEvent<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetEventRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_GetEventRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_GetEventResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetEventResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_SentryService.Method.GetEvent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetEvents" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetEventsRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_GetEventsRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_GetEventsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getEvents<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetEventsRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_GetEventsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_GetEventsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetEventsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_SentryService.Method.GetEvents.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetSentryMode" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetSentryModeRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetSentryModeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setSentryMode<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetSentryModeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetSentryModeResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_SentryService.Method.SetSentryMode.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetEnhancedDeterrence" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetEnhancedDeterrenceRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetEnhancedDeterrenceRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetEnhancedDeterrenceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setEnhancedDeterrence<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_SentryService.Method.SetEnhancedDeterrence.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetSentryModeAtHome" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeAtHomeRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetSentryModeAtHomeRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetSentryModeAtHomeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setSentryModeAtHome<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetSentryModeAtHomeResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_SentryService.Method.SetSentryModeAtHome.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetSentryModeAtWork" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeAtWorkRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetSentryModeAtWorkRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetSentryModeAtWorkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setSentryModeAtWork<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetSentryModeAtWorkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_SentryService.Method.SetSentryModeAtWork.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "TurnOffSentryAlarm" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_TurnOffSentryAlarmRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_TurnOffSentryAlarmRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_TurnOffSentryAlarmResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func turnOffSentryAlarm<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_TurnOffSentryAlarmResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_SentryService.Method.TurnOffSentryAlarm.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Mobilegateway_Protos_SentryService.ClientProtocol {
    /// Call the "GetEvent" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_GetEventRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getEvent<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetEventRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetEventResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getEvent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_GetEventRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_GetEventResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetEvents" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_GetEventsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getEvents<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetEventsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetEventsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getEvents(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_GetEventsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_GetEventsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetSentryMode" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setSentryMode<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setSentryMode(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetSentryModeRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetSentryModeResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetEnhancedDeterrence" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_SetEnhancedDeterrenceRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setEnhancedDeterrence<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setEnhancedDeterrence(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetSentryModeAtHome" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeAtHomeRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setSentryModeAtHome<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeAtHomeRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setSentryModeAtHome(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetSentryModeAtHomeRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetSentryModeAtHomeResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetSentryModeAtWork" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_SetSentryModeAtWorkRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setSentryModeAtWork<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeAtWorkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setSentryModeAtWork(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetSentryModeAtWorkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetSentryModeAtWorkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TurnOffSentryAlarm" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_TurnOffSentryAlarmRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func turnOffSentryAlarm<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_TurnOffSentryAlarmRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.turnOffSentryAlarm(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_TurnOffSentryAlarmRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_TurnOffSentryAlarmResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Mobilegateway_Protos_SentryService.ClientProtocol {
    /// Call the "GetEvent" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getEvent<Result>(
        _ message: Mobilegateway_Protos_GetEventRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetEventResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_GetEventRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getEvent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetEvents" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getEvents<Result>(
        _ message: Mobilegateway_Protos_GetEventsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetEventsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_GetEventsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getEvents(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetSentryMode" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setSentryMode<Result>(
        _ message: Mobilegateway_Protos_SetSentryModeRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setSentryMode(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetEnhancedDeterrence" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setEnhancedDeterrence<Result>(
        _ message: Mobilegateway_Protos_SetEnhancedDeterrenceRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetEnhancedDeterrenceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_SetEnhancedDeterrenceRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setEnhancedDeterrence(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetSentryModeAtHome" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setSentryModeAtHome<Result>(
        _ message: Mobilegateway_Protos_SetSentryModeAtHomeRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeAtHomeResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeAtHomeRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setSentryModeAtHome(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetSentryModeAtWork" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setSentryModeAtWork<Result>(
        _ message: Mobilegateway_Protos_SetSentryModeAtWorkRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetSentryModeAtWorkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_SetSentryModeAtWorkRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setSentryModeAtWork(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TurnOffSentryAlarm" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func turnOffSentryAlarm<Result>(
        _ message: Mobilegateway_Protos_TurnOffSentryAlarmRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_TurnOffSentryAlarmResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_TurnOffSentryAlarmRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.turnOffSentryAlarm(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}