// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: user_profile_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - mobilegateway.protos.UserProfileService

/// Namespace containing generated types for the "mobilegateway.protos.UserProfileService" service.
public enum Mobilegateway_Protos_UserProfileService {
    /// Service descriptor for the "mobilegateway.protos.UserProfileService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.UserProfileService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "GetUserProfile" metadata.
        public enum GetUserProfile {
            /// Request type for "GetUserProfile".
            public typealias Input = Mobilegateway_Protos_GetUserProfileRequest
            /// Response type for "GetUserProfile".
            public typealias Output = Mobilegateway_Protos_GetUserProfileResponse
            /// Descriptor for "GetUserProfile".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.UserProfileService"),
                method: "GetUserProfile"
            )
        }
        /// Namespace for "SetUserProfile" metadata.
        public enum SetUserProfile {
            /// Request type for "SetUserProfile".
            public typealias Input = Mobilegateway_Protos_SetUserProfileRequest
            /// Response type for "SetUserProfile".
            public typealias Output = Mobilegateway_Protos_SetUserProfileResponse
            /// Descriptor for "SetUserProfile".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.UserProfileService"),
                method: "SetUserProfile"
            )
        }
        /// Namespace for "UploadUserProfilePhoto" metadata.
        public enum UploadUserProfilePhoto {
            /// Request type for "UploadUserProfilePhoto".
            public typealias Input = Mobilegateway_Protos_UploadUserProfilePhotoRequest
            /// Response type for "UploadUserProfilePhoto".
            public typealias Output = Mobilegateway_Protos_UploadUserProfilePhotoResponse
            /// Descriptor for "UploadUserProfilePhoto".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.UserProfileService"),
                method: "UploadUserProfilePhoto"
            )
        }
        /// Namespace for "ReferralHistoryApi" metadata.
        public enum ReferralHistoryApi {
            /// Request type for "ReferralHistoryApi".
            public typealias Input = Mobilegateway_Protos_ReferralHistoryApiRequest
            /// Response type for "ReferralHistoryApi".
            public typealias Output = Mobilegateway_Protos_ReferralHistoryApiResponse
            /// Descriptor for "ReferralHistoryApi".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.UserProfileService"),
                method: "ReferralHistoryApi"
            )
        }
        /// Descriptors for all methods in the "mobilegateway.protos.UserProfileService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetUserProfile.descriptor,
            SetUserProfile.descriptor,
            UploadUserProfilePhoto.descriptor,
            ReferralHistoryApi.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "mobilegateway.protos.UserProfileService" service.
    public static let mobilegateway_protos_UserProfileService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "mobilegateway.protos.UserProfileService")
}

// MARK: mobilegateway.protos.UserProfileService (server)

extension Mobilegateway_Protos_UserProfileService {
    /// Streaming variant of the service protocol for the "mobilegateway.protos.UserProfileService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_GetUserProfileRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_GetUserProfileResponse` messages.
        func getUserProfile(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_GetUserProfileRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_GetUserProfileResponse>

        /// Handle the "SetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_SetUserProfileRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_SetUserProfileResponse` messages.
        func setUserProfile(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetUserProfileRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetUserProfileResponse>

        /// Handle the "UploadUserProfilePhoto" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_UploadUserProfilePhotoRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_UploadUserProfilePhotoResponse` messages.
        func uploadUserProfilePhoto(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse>

        /// Handle the "ReferralHistoryApi" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Mobilegateway_Protos_ReferralHistoryApiRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Mobilegateway_Protos_ReferralHistoryApiResponse` messages.
        func referralHistoryApi(
            request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_ReferralHistoryApiRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_ReferralHistoryApiResponse>
    }

    /// Service protocol for the "mobilegateway.protos.UserProfileService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Mobilegateway_Protos_UserProfileService.StreamingServiceProtocol {
        /// Handle the "GetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetUserProfileRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_GetUserProfileResponse` message.
        func getUserProfile(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_GetUserProfileRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_GetUserProfileResponse>

        /// Handle the "SetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetUserProfileRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_SetUserProfileResponse` message.
        func setUserProfile(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetUserProfileRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetUserProfileResponse>

        /// Handle the "UploadUserProfilePhoto" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_UploadUserProfilePhotoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_UploadUserProfilePhotoResponse` message.
        func uploadUserProfilePhoto(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse>

        /// Handle the "ReferralHistoryApi" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_ReferralHistoryApiRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Mobilegateway_Protos_ReferralHistoryApiResponse` message.
        func referralHistoryApi(
            request: GRPCCore.ServerRequest<Mobilegateway_Protos_ReferralHistoryApiRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_ReferralHistoryApiResponse>
    }

    /// Simple service protocol for the "mobilegateway.protos.UserProfileService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Mobilegateway_Protos_UserProfileService.ServiceProtocol {
        /// Handle the "GetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_GetUserProfileRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_GetUserProfileResponse` to respond with.
        func getUserProfile(
            request: Mobilegateway_Protos_GetUserProfileRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_GetUserProfileResponse

        /// Handle the "SetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_SetUserProfileRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_SetUserProfileResponse` to respond with.
        func setUserProfile(
            request: Mobilegateway_Protos_SetUserProfileRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_SetUserProfileResponse

        /// Handle the "UploadUserProfilePhoto" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_UploadUserProfilePhotoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_UploadUserProfilePhotoResponse` to respond with.
        func uploadUserProfilePhoto(
            request: Mobilegateway_Protos_UploadUserProfilePhotoRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_UploadUserProfilePhotoResponse

        /// Handle the "ReferralHistoryApi" method.
        ///
        /// - Parameters:
        ///   - request: A `Mobilegateway_Protos_ReferralHistoryApiRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Mobilegateway_Protos_ReferralHistoryApiResponse` to respond with.
        func referralHistoryApi(
            request: Mobilegateway_Protos_ReferralHistoryApiRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Mobilegateway_Protos_ReferralHistoryApiResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Mobilegateway_Protos_UserProfileService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Mobilegateway_Protos_UserProfileService.Method.GetUserProfile.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_GetUserProfileRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_GetUserProfileResponse>(),
            handler: { request, context in
                try await self.getUserProfile(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_UserProfileService.Method.SetUserProfile.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetUserProfileRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetUserProfileResponse>(),
            handler: { request, context in
                try await self.setUserProfile(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_UserProfileService.Method.UploadUserProfilePhoto.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_UploadUserProfilePhotoRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_UploadUserProfilePhotoResponse>(),
            handler: { request, context in
                try await self.uploadUserProfilePhoto(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Mobilegateway_Protos_UserProfileService.Method.ReferralHistoryApi.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_ReferralHistoryApiRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_ReferralHistoryApiResponse>(),
            handler: { request, context in
                try await self.referralHistoryApi(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Mobilegateway_Protos_UserProfileService.ServiceProtocol {
    public func getUserProfile(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_GetUserProfileRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_GetUserProfileResponse> {
        let response = try await self.getUserProfile(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func setUserProfile(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_SetUserProfileRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_SetUserProfileResponse> {
        let response = try await self.setUserProfile(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func uploadUserProfilePhoto(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse> {
        let response = try await self.uploadUserProfilePhoto(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func referralHistoryApi(
        request: GRPCCore.StreamingServerRequest<Mobilegateway_Protos_ReferralHistoryApiRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Mobilegateway_Protos_ReferralHistoryApiResponse> {
        let response = try await self.referralHistoryApi(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Mobilegateway_Protos_UserProfileService.SimpleServiceProtocol {
    public func getUserProfile(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_GetUserProfileRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_GetUserProfileResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_GetUserProfileResponse>(
            message: try await self.getUserProfile(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func setUserProfile(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_SetUserProfileRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_SetUserProfileResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_SetUserProfileResponse>(
            message: try await self.setUserProfile(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func uploadUserProfilePhoto(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse>(
            message: try await self.uploadUserProfilePhoto(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func referralHistoryApi(
        request: GRPCCore.ServerRequest<Mobilegateway_Protos_ReferralHistoryApiRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Mobilegateway_Protos_ReferralHistoryApiResponse> {
        return GRPCCore.ServerResponse<Mobilegateway_Protos_ReferralHistoryApiResponse>(
            message: try await self.referralHistoryApi(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: mobilegateway.protos.UserProfileService (client)

extension Mobilegateway_Protos_UserProfileService {
    /// Generated client protocol for the "mobilegateway.protos.UserProfileService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetUserProfileRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_GetUserProfileRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_GetUserProfileResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getUserProfile<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetUserProfileRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_GetUserProfileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_GetUserProfileResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetUserProfileResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetUserProfileRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetUserProfileRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetUserProfileResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setUserProfile<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetUserProfileRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetUserProfileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetUserProfileResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetUserProfileResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UploadUserProfilePhoto" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_UploadUserProfilePhotoRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_UploadUserProfilePhotoRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_UploadUserProfilePhotoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func uploadUserProfilePhoto<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_UploadUserProfilePhotoResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ReferralHistoryApi" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_ReferralHistoryApiRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_ReferralHistoryApiRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_ReferralHistoryApiResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func referralHistoryApi<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_ReferralHistoryApiRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_ReferralHistoryApiRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_ReferralHistoryApiResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_ReferralHistoryApiResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "mobilegateway.protos.UserProfileService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_GetUserProfileRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_GetUserProfileRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_GetUserProfileResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getUserProfile<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetUserProfileRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_GetUserProfileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_GetUserProfileResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetUserProfileResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_UserProfileService.Method.GetUserProfile.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetUserProfile" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_SetUserProfileRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_SetUserProfileRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_SetUserProfileResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setUserProfile<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetUserProfileRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_SetUserProfileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_SetUserProfileResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetUserProfileResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_UserProfileService.Method.SetUserProfile.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UploadUserProfilePhoto" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_UploadUserProfilePhotoRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_UploadUserProfilePhotoRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_UploadUserProfilePhotoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func uploadUserProfilePhoto<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_UploadUserProfilePhotoResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_UserProfileService.Method.UploadUserProfilePhoto.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ReferralHistoryApi" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Mobilegateway_Protos_ReferralHistoryApiRequest` message.
        ///   - serializer: A serializer for `Mobilegateway_Protos_ReferralHistoryApiRequest` messages.
        ///   - deserializer: A deserializer for `Mobilegateway_Protos_ReferralHistoryApiResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func referralHistoryApi<Result>(
            request: GRPCCore.ClientRequest<Mobilegateway_Protos_ReferralHistoryApiRequest>,
            serializer: some GRPCCore.MessageSerializer<Mobilegateway_Protos_ReferralHistoryApiRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Mobilegateway_Protos_ReferralHistoryApiResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_ReferralHistoryApiResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Mobilegateway_Protos_UserProfileService.Method.ReferralHistoryApi.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Mobilegateway_Protos_UserProfileService.ClientProtocol {
    /// Call the "GetUserProfile" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_GetUserProfileRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getUserProfile<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_GetUserProfileRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetUserProfileResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getUserProfile(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_GetUserProfileRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_GetUserProfileResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetUserProfile" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_SetUserProfileRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setUserProfile<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_SetUserProfileRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetUserProfileResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setUserProfile(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_SetUserProfileRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_SetUserProfileResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UploadUserProfilePhoto" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_UploadUserProfilePhotoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func uploadUserProfilePhoto<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_UploadUserProfilePhotoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.uploadUserProfilePhoto(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_UploadUserProfilePhotoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_UploadUserProfilePhotoResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ReferralHistoryApi" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Mobilegateway_Protos_ReferralHistoryApiRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func referralHistoryApi<Result>(
        request: GRPCCore.ClientRequest<Mobilegateway_Protos_ReferralHistoryApiRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_ReferralHistoryApiResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.referralHistoryApi(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Mobilegateway_Protos_ReferralHistoryApiRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Mobilegateway_Protos_ReferralHistoryApiResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Mobilegateway_Protos_UserProfileService.ClientProtocol {
    /// Call the "GetUserProfile" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getUserProfile<Result>(
        _ message: Mobilegateway_Protos_GetUserProfileRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_GetUserProfileResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_GetUserProfileRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getUserProfile(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetUserProfile" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setUserProfile<Result>(
        _ message: Mobilegateway_Protos_SetUserProfileRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_SetUserProfileResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_SetUserProfileRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.setUserProfile(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UploadUserProfilePhoto" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func uploadUserProfilePhoto<Result>(
        _ message: Mobilegateway_Protos_UploadUserProfilePhotoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_UploadUserProfilePhotoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_UploadUserProfilePhotoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.uploadUserProfilePhoto(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ReferralHistoryApi" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func referralHistoryApi<Result>(
        _ message: Mobilegateway_Protos_ReferralHistoryApiRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Mobilegateway_Protos_ReferralHistoryApiResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Mobilegateway_Protos_ReferralHistoryApiRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.referralHistoryApi(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}